image:
  repository: ritazh/secrets-store-csi
  tag: v0.0.3
  pullPolicy: Always

## `provider` should be one of azure, etc...
provider: azure
logLevel: 

## Install Default RBAC roles and bindings
rbac:
  install: true
