image:
  repository: docker.io/deislabs/secrets-store-csi
  tag: v0.0.5
  pullPolicy: Always

logLevel: 

## Install Default RBAC roles and bindings
rbac:
  install: true

providers:
  azure: false
  vault: false
