image:
  repository: docker.io/deislabs/secrets-store-csi
  tag: v0.0.7
  pullPolicy: Always

logLevel:
  debug: true

livenessProbe:
  port: 9808

## Install Default RBAC roles and bindings
rbac:
  install: true

## Minimum Provider Versions (optional)
minimumProviderVersions:
