run:
  deadline: 3m
  skip-dirs:
  skip-files:

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosimple
    - golint
    - govet
    - ineffassign
    - misspell
    - unused
