language: go
go_import_path: github.com/deislabs/secrets-store-csi-driver
dist: bionic

services:
  - docker

env:
  global:
    - GO111MODULE=on

go:
  - "1.12.x"

jobs:
  include:
    - stage: test
      name: "linting rules"
      script:
        - make test-style
    - stage: test
      name: "unit test"
      script:
        - make test
    - stage: test
      name: "sanity test"
      install:
        - sudo apt update && sudo apt install cifs-utils procps -y
      script: sudo -E env "PATH=$PATH" make sanity-test
    - stage: test
      name: "e2e-vault"
      before_script:
        - make e2e-bootstrap
      script:
        - export KUBECONFIG=$(kind get kubeconfig-path)
        - make e2e-vault
    - stage: test
      name: "e2e-azure"
      if: branch = master AND repo = deislabs/secrets-store-csi-driver AND type != pull_request
      before_script:
        - make e2e-bootstrap
      script:
        - export KUBECONFIG=$(kind get kubeconfig-path)
        - make e2e-azure
    - stage: "build, deploy"
      script:
        - make build
      deploy:
        - provider: script
          skip_cleanup: true
          script: make ci-deploy
          on:
            repo: deislabs/secrets-store-csi-driver
            branch: master
            tags: true
