kind: Service
apiVersion: v1
metadata:
  name: csi-secrets-store-attacher
  namespace: {{ .Release.Namespace }}
{{ include "sscd.labels" . | indent 2 }}
spec:
  selector:
    app: {{ template "sscd.name" . }}
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-secrets-store-attacher
  namespace: {{ .Release.Namespace }}
{{ include "sscd.labels" . | indent 2 }}
spec:
  serviceName: "csi-secrets-store-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sscd.name" . }}
  template:
    metadata:
{{ include "sscd.labels" . | indent 6 }}
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: gcr.io/gke-release/csi-attacher:v1.0.0-gke.0
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-secrets-store
            type: DirectoryOrCreate
          name: socket-dir
