{{ if .Values.rbac.install }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: secretproviderclasses-role
rules:
- apiGroups:
  - secrets-store.csi.k8s.com
  resources:
  - secretproviderclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets-store.csi.k8s.com
  resources:
  - secretproviderclasses/status
  verbs:
  - get
  - patch
  - update
{{ end }}
