version: 2

defaults: &defaults
  working_directory: /go/src/github.com/deislabs/secrets-store-csi-driver
  docker:
    - image: quay.io/deis/go-dev:v1.18.2
  environment:
    GOPATH: /go

experimental:
  notify:
    branches:
      only:
        - master
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: |
          echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run:
          name: Run linting rules
          command: make test-style
      - run:
          name: Run tests
          command: make test
      # TODO (aramase) add sanity check as part of CI using travis as running docker
      # in privileged mode is not allowed in circleci unless executor type is machine.
      #- run:
      #    name: Run sanity test
      #    command: make sanity-test
      - run:
          name: Build
          command: make build
workflows:
  version: 2
  build_and_test_pr:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  build_and_test_master:
    jobs:
      - test:
          filters:
            branches:
              only: master

