kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-secrets-store
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-secrets-store
  storageClassName: ""
