kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-keyvault
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-keyvault
  storageClassName: ""
