{{- if .Values.windows.enabled}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ template "sscd.fullname" . }}-windows
  namespace: {{ .Release.Namespace }}
{{ include "sscd.labels" . | indent 2 }}
{{- if .Values.windows.annotations }}
  annotations:
{{ toYaml .Values.windows.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "sscd.name" . }}
  updateStrategy:
{{ toYaml .Values.windows.updateStrategy | indent 4 }}
  template:
    metadata:
{{ include "sscd.labels" . | indent 6 }}
    spec:
      serviceAccountName: secrets-store-csi-driver
      containers:
        - name: node-driver-registrar
          image: "{{ .Values.windows.registrarImage.repository }}:{{ .Values.windows.registrarImage.tag }}"
          args:
            - --v=5
            - "--csi-address=unix://C:\\csi\\csi.sock"
            - --kubelet-registration-path={{ .Values.windows.kubeletRootDir }}\plugins\csi-secrets-store\csi.sock
          env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.windows.registrarImage.pullPolicy }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
            - name: registration-dir
              mountPath: C:\registration
{{- with .Values.windows.registrar.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
        - name: secrets-store
          image: "{{ .Values.windows.image.repository }}:{{ .Values.windows.image.tag }}"
          args:
            {{- if .Values.logVerbosity }}
            - -v={{ .Values.logVerbosity }}
            {{- end }}
            {{- if .Values.logFormatJSON }}
            - --log-format-json={{ .Values.logFormatJSON }}
            {{- end }}
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--provider-volume=C:\\k\\secrets-store-csi-providers"
            {{- if and (semverCompare ">= v0.0.9-0" .Values.windows.image.tag) .Values.minimumProviderVersions }}
            - "--min-provider-version={{ .Values.minimumProviderVersions }}"
            {{- end }}
            {{- if and (semverCompare ">= v0.0.14-0" .Values.windows.image.tag) .Values.grpcSupportedProviders }}
            - "--grpc-supported-providers={{ .Values.grpcSupportedProviders }}"
            {{- end }}
            {{- if and (semverCompare ">= v0.0.15-0" .Values.windows.image.tag) .Values.enableSecretRotation }}
            - "--enable-secret-rotation={{ .Values.enableSecretRotation }}"
            {{- end }}
            {{- if and (semverCompare ">= v0.0.15-0" .Values.windows.image.tag) .Values.rotationPollInterval }}
            - "--rotation-poll-interval={{ .Values.rotationPollInterval }}"
            {{- end }}
            - "--metrics-addr={{ .Values.windows.metricsAddr }}"
            {{- if .Values.windows.prometheusPort }}
            - "--prometheus-port={{ .Values.windows.prometheusPort }}"
            {{- end }}
          env:
          {{- with .Values.windows.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: CSI_ENDPOINT
            value: unix://C:\\csi\\csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.windows.image.pullPolicy }}
          securityContext:
            privileged: true
          {{- if semverCompare ">= v0.0.9-0" .Values.windows.image.tag }}
          ports:
            - containerPort: {{ .Values.livenessProbe.port }}
              name: healthz
              protocol: TCP
          livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /healthz
                port: healthz
              initialDelaySeconds: 30
              timeoutSeconds: 10
              periodSeconds: 15
          {{- end }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
            - name: mountpoint-dir
              mountPath: {{ .Values.windows.kubeletRootDir }}\pods
              mountPropagation: Bidirectional
            - name: providers-dir
              mountPath: C:\k\secrets-store-csi-providers
{{- with .Values.windows.driver.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
        {{- if semverCompare ">= v0.0.9-0" .Values.windows.image.tag }}
        - name: liveness-probe
          image: "{{ .Values.windows.livenessProbeImage.repository }}:{{ .Values.windows.livenessProbeImage.tag }}"
          imagePullPolicy: {{ .Values.windows.livenessProbeImage.pullPolicy }}
          args:
          - "--csi-address=unix://C:\\csi\\csi.sock"
          - --probe-timeout=3s
          - --health-port={{ .Values.livenessProbe.port }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
{{- with .Values.windows.livenessProbe.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
        {{- end }}
      {{- if .Values.windows.priorityClassName }}
      priorityClassName: {{ .Values.windows.priorityClassName | quote }}
      {{- end }}
      volumes:
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\pods\
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\plugins_registry\
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\plugins\csi-secrets-store\
            type: DirectoryOrCreate
        - name: providers-dir
          hostPath:
            path: C:\k\secrets-store-csi-providers\
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: windows
{{- if .Values.windows.nodeSelector }}
{{- toYaml .Values.windows.nodeSelector | nindent 8 }}
{{- end }}
{{- with .Values.windows.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end -}}
